version: '3.7'

x-email-alert-api: &email-alert-api
  build:
    context: .
    dockerfile: services/email-alert-api/Dockerfile
  image: email-alert-api
  volumes:
    - ..:/govuk:delegated
    - bundle:/usr/local/bundle
  working_dir: /govuk/email-alert-api

services:
  email-alert-api-default:
    <<: *email-alert-api
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/email-alert-api"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/email-alert-api-test"
      REDIS_URL: redis://redis

  email-alert-api-backend: &email-alert-api-backend
    <<: *email-alert-api
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/email-alert-api"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: email-alert-api.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid

  email-alert-api-worker:
    <<: *email-alert-api
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/email-alert-api"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
