version: '3.7'

volumes:
  govuk-account-manager-prototype-tmp:

x-govuk-account-manager-prototype: &govuk-account-manager-prototype
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk-account-manager-prototype
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - govuk-account-manager-prototype-tmp:/govuk/govuk-account-manager-prototype/tmp
  working_dir: /govuk/govuk-account-manager-prototype

services:
  govuk-account-manager-prototype-lite:
    <<: *govuk-account-manager-prototype
    depends_on:
      - postgres-9.6
      - memcached
    environment:
      ACCOUNT_API_DOORKEEPER_UID: client-id
      MEMCACHE_SERVERS: memcached
      DATABASE_URL: "postgresql://postgres@postgres-9.6/govuk-account-manager-prototype"
      TEST_DATABASE_URL: "postgresql://postgres@postgres-9.6/govuk-account-manager-prototype-test"
      REDIRECT_BASE_URL: http://www.login.service.dev.gov.uk

  govuk-account-manager-prototype-app: &govuk-account-manager-prototype-app
    <<: *govuk-account-manager-prototype
    depends_on:
      - nginx-proxy
      - postgres-9.6
      - redis
      - govuk-attribute-service-prototype-app
      - govuk-account-manager-prototype-worker
    environment:
      ACCOUNT_API_DOORKEEPER_UID: client-id
      ASSET_HOST: www.login.service.dev.gov.uk
      VIRTUAL_HOST: www.login.service.dev.gov.uk
      BINDING: 0.0.0.0
      MEMCACHE_SERVERS: memcached
      DATABASE_URL: "postgresql://postgres@postgres-9.6/govuk-account-manager-prototype"
      ATTRIBUTE_SERVICE_URL: http://attributes.login.service.dev.gov.uk
      REDIRECT_BASE_URL: http://www.login.service.dev.gov.uk
      REDIS_URL: redis://redis:6379/0
    expose:
      - "3000"
    command: bin/rails s --restart

  govuk-account-manager-prototype-worker:
    <<: *govuk-account-manager-prototype
    depends_on:
      - redis
      - govuk-attribute-service-prototype-app
    environment:
      ACCOUNT_API_DOORKEEPER_UID: client-id
      ATTRIBUTE_SERVICE_URL: http://attributes.login.service.dev.gov.uk
      REDIS_URL: redis://redis:6379/0
      REDIRECT_BASE_URL: http://www.login.service.dev.gov.uk
      DATABASE_URL: "postgresql://postgres@postgres-9.6/govuk-account-manager-prototype"
    command: bundle exec sidekiq -C ./config/sidekiq.yml
