version: '3.7'

x-support-api: &support-api
  build:
    context: .
    dockerfile: support-api/Dockerfile
  image: support-api
  volumes:
    - ..:/govuk:delegated
    - bundle:/usr/local/bundle
    - home:/home/build
    - ./support-api/database.yml:/govuk/support-api/config/database.yml
  working_dir: /govuk/support-api

services:
  support-api-default:
    <<: *support-api
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/support-api"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/support-api-test"
      REDIS_URL: redis://redis
      PATH: "/govuk/support-api/bin:${PATH}"

  support-api-backend: &support-api-backend
    <<: *support-api
    depends_on:
      - postgres
      - redis
      - nginx-proxy
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/support-api"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: support-api.dev.gov.uk
      HOST: 0.0.0.0
      PATH: "/govuk/support-api/bin:${PATH}"
    ports:
      - "3000"
    command: rails s -P /tmp/rails.pid
