version: '3.7'

x-calendars: &calendars
  build:
    context: .
    dockerfile: services/calendars/Dockerfile
  image: calendars
  volumes:
    - ..:/govuk:delegated
    - bundle:/usr/local/bundle
  working_dir: /govuk/calendars

services:
  calendars-lite:
    <<: *calendars
    volumes:
      - ..:/govuk:delegated
      - bundle:/usr/local/bundle

  calendars-app: &calendars-app
    <<: *calendars
    depends_on:
      - router-app
      - content-store-app
      - static-app
    environment:
      GOVUK_ASSET_ROOT: calendars.dev.gov.uk
      VIRTUAL_HOST: calendars.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid

  calendars-app-draft:
    <<: *calendars-app
    depends_on:
      - router-app-draft
      - content-store-app-draft
      - static-app-draft
    environment:
      GOVUK_ASSET_ROOT: draft-calendars.dev.gov.uk
      VIRTUAL_HOST: draft-calendars.dev.gov.uk
      PLEK_HOSTNAME_PREFIX: "draft-"
      HOST: 0.0.0.0

  calendars-setup:
    <<: *calendars
    depends_on:
      - publishing-api-e2e
