version: '3.7'

x-support: &support
  build:
    context: .
    dockerfile: services/support/Dockerfile
  image: support
  volumes:
    - ..:/govuk:delegated
    - bundle:/usr/local/bundle
    - home:/home/build
  working_dir: /govuk/support

services:
  support-lite:
    <<: *support
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis

  support-app: &support-app
    <<: *support
    depends_on:
      - redis
      - nginx-proxy-app
      - support-api-app
    environment:
      VIRTUAL_HOST: support.dev.gov.uk
      REDIS_URL: redis://redis
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s -P /tmp/rails.pid
