version: '3.7'

x-govuk-cdn-config: &govuk-cdn-config
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk-cdn-config
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/govuk-cdn-config

services:
  govuk-cdn-config-lite:
    <<: *govuk-cdn-config
