version: '3.7'
  
volumes:
  mapit-pg:

x-mapit: &mapit
  build:
    context: .
    dockerfile: services/mapit/Dockerfile
  image: mapit
  working_dir: /mapit

services:
  mapit-pg:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - mapit-pg:/var/lib/postgresql/data

  mapit:
    <<: *mapit
    volumes:
        - ~/govuk/mapit:/mapit
    depends_on:
      - mapit-pg
      - nginx-proxy-app
    working_dir: /mapit
    environment:
      MAPIT_DB_PASS: ''
      DJANGO_SECRET_KEY: 'secret'
      MAPIT_DB_HOST: 'mapit-pg'
      PGHOST: "mapit-pg"
      VIRTUAL_HOST: mapit.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3108:3108"
    command: bash -c "python ./manage.py runserver 0.0.0.0:3108"
