version: '3.7'

x-search-api: &search-api
  build:
    context: .
    dockerfile: services/search-api/Dockerfile
  image: search-api
  volumes:
    - ..:/govuk:delegated
    - bundle:/usr/local/bundle
    - home:/home/build
  working_dir: /govuk/search-api

services:
  search-api-lite:
    <<: *search-api
    depends_on:
      - redis
      - elasticsearch5
      - elasticsearch6
    environment:
      REDIS_HOST: redis
      ELASTICSEARCH_URI: http://elasticsearch5:9200
      ELASTICSEARCH_B_URI: http://elasticsearch6:9200

  search-api-app: &search-api-app
    <<: *search-api
    depends_on:
      - nginx-proxy-app
      - redis
      - elasticsearch5
      - elasticsearch6
    environment:
      REDIS_HOST: redis
      ELASTICSEARCH_URI: http://elasticsearch5:9200
      ELASTICSEARCH_B_URI: http://elasticsearch6:9200
      VIRTUAL_HOST: search-api.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bundle exec mr-sparkle --force-polling -- -p 3000


