version: '3.7'

x-govuk-lint: &govuk-lint
  build:
    context: .
    dockerfile: services/govuk-lint/Dockerfile
  image: govuk-lint
  volumes:
    - ..:/govuk:delegated
    - bundle:/usr/local/bundle
    - home:/home/build
  working_dir: /govuk/govuk-lint

services:
  govuk-lint-lite:
    <<: *govuk-lint
