version: '3.7'

x-govuk-lint: &govuk-lint
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk-lint
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/govuk-lint

services:
  govuk-lint-lite:
    <<: *govuk-lint
